spring:
  config:
    import:
      - optional:file:env/security.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
      show-sql: true
    hibernate:
      ddl-auto: update

hantu:
  api:
    url: ${HANTU_BASEURL}
    appkey: ${HANTU_APPKEY}
    appsecret: ${HANTU_APPSECRET}

youtube:
  api:
    key: ${YOUTUBE_KEY}

discord:
  token: ${DISCORD_TOKEN}

fastapi:
  url: ${FASTAPI_URL}

gpt:
  api:
    key: ${GPT_KEY}
    texturl: ${GPT_TEXTURL}
    mainurl: ${GPT_MAINURL}
    prompt: ${GPT_PROMPT}
    mainprompt: ${GPT_MAINPROMPT}


server:
  port: ${SERVER_PORT1}